// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github/kunhou/gl_exercise/internal/common/config"
	"github/kunhou/gl_exercise/internal/deliver/http/router"
	"github/kunhou/gl_exercise/internal/deliver/http/server"
	"github/kunhou/gl_exercise/internal/pkg/srvmgmt"
	"github/kunhou/gl_exercise/internal/repository/task"
	task2 "github/kunhou/gl_exercise/internal/service/task"
)

// Injectors from wire.go:

// initApplication init application.
func initApplication(debug bool, serverConf *config.Server) (*srvmgmt.Application, func(), error) {
	iTaskRepository := task.NewTaskRepo()
	iTaskService := task2.New(iTaskRepository)
	taskRouter := router.NewTaskRouter(iTaskService)
	engine := server.NewHTTPServer(debug, taskRouter)
	application := newApplication(serverConf, engine)
	return application, func() {
	}, nil
}
